import { Product } from '@/types/product';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'PHANTOM X1 ELITE',
    slug: 'phantom-x1-elite',
    category: 'gaming',
    price: 289990,
    salePrice: 249990,
    image: '/images/pc-1.png',
    specs: {
      processor: 'Intel Core i9-14900K',
      graphics: 'RTX 4090 24GB',
      ram: '64GB DDR5',
      storage: '2TB NVMe SSD',
    },
    badges: ['ТОП', 'СКИДКА'],
    inStock: true,
    popularity: 98,
  },
  {
    id: '2',
    name: 'SHADOW STRIKE PRO',
    slug: 'shadow-strike-pro',
    category: 'gaming',
    price: 189990,
    image: '/images/pc-2.png',
    specs: {
      processor: 'Intel Core i7-14700K',
      graphics: 'RTX 4080 Super 16GB',
      ram: '32GB DDR5',
      storage: '1TB NVMe SSD',
    },
    badges: ['ХИТЫ'],
    inStock: true,
    popularity: 95,
  },
  {
    id: '3',
    name: 'CYBER WARRIOR V2',
    slug: 'cyber-warrior-v2',
    category: 'gaming',
    price: 149990,
    salePrice: 139990,
    image: '/images/pc-3.png',
    specs: {
      processor: 'AMD Ryzen 7 7800X3D',
      graphics: 'RTX 4070 Ti Super 16GB',
      ram: '32GB DDR5',
      storage: '1TB NVMe SSD',
    },
    badges: ['ИГРЫ'],
    inStock: true,
    popularity: 92,
  },
  {
    id: '4',
    name: 'STORM BREAKER',
    slug: 'storm-breaker',
    category: 'gaming',
    price: 119990,
    image: '/images/pc-4.png',
    specs: {
      processor: 'Intel Core i5-14600K',
      graphics: 'RTX 4070 12GB',
      ram: '32GB DDR5',
      storage: '1TB NVMe SSD',
    },
    inStock: true,
    popularity: 88,
  },
  {
    id: '5',
    name: 'VORTEX STREAM',
    slug: 'vortex-stream',
    category: 'streaming',
    price: 229990,
    image: '/images/pc-5.png',
    specs: {
      processor: 'Intel Core i9-14900K',
      graphics: 'RTX 4080 Super 16GB',
      ram: '64GB DDR5',
      storage: '4TB NVMe SSD',
    },
    badges: ['СТРИМ'],
    inStock: true,
    popularity: 90,
  },
  {
    id: '6',
    name: 'CREATOR STUDIO',
    slug: 'creator-studio',
    category: 'workstation',
    price: 349990,
    image: '/images/pc-6.png',
    specs: {
      processor: 'AMD Ryzen 9 7950X',
      graphics: 'RTX 4090 24GB',
      ram: '128GB DDR5',
      storage: '8TB NVMe SSD',
    },
    badges: ['РЕНДЕР'],
    inStock: true,
    popularity: 85,
  },
  {
    id: '7',
    name: 'BLAZE RUNNER',
    slug: 'blaze-runner',
    category: 'gaming',
    price: 99990,
    salePrice: 89990,
    image: '/images/pc-7.png',
    specs: {
      processor: 'AMD Ryzen 5 7600X',
      graphics: 'RTX 4060 Ti 16GB',
      ram: '16GB DDR5',
      storage: '512GB NVMe SSD',
    },
    badges: ['СТАРТ'],
    inStock: true,
    popularity: 82,
  },
  {
    id: '8',
    name: 'TITAN FORGE',
    slug: 'titan-forge',
    category: 'workstation',
    price: 259990,
    image: '/images/pc-8.png',
    specs: {
      processor: 'Intel Core i9-14900K',
      graphics: 'RTX 4080 Super 16GB',
      ram: '64GB DDR5',
      storage: '2TB NVMe SSD',
    },
    badges: ['МОЩЬ'],
    inStock: false,
    popularity: 78,
  },
  {
    id: '9',
    name: 'ECLIPSE CORE',
    slug: 'eclipse-core',
    category: 'gaming',
    price: 169990,
    image: '/images/pc-9.png',
    specs: {
      processor: 'AMD Ryzen 7 7800X3D',
      graphics: 'RTX 4070 Ti Super 16GB',
      ram: '32GB DDR5',
      storage: '2TB NVMe SSD',
    },
    inStock: true,
    popularity: 86,
  },
];

export const filterOptions = {
  categories: [
    { value: 'gaming', label: 'Игровые ПК' },
    { value: 'workstation', label: 'Рабочие станции' },
    { value: 'streaming', label: 'Для стриминга' },
  ],
  processors: [
    { value: 'Intel Core i5', label: 'Intel Core i5' },
    { value: 'Intel Core i7', label: 'Intel Core i7' },
    { value: 'Intel Core i9', label: 'Intel Core i9' },
    { value: 'AMD Ryzen 5', label: 'AMD Ryzen 5' },
    { value: 'AMD Ryzen 7', label: 'AMD Ryzen 7' },
    { value: 'AMD Ryzen 9', label: 'AMD Ryzen 9' },
  ],
  graphics: [
    { value: 'RTX 4060', label: 'GeForce RTX 4060' },
    { value: 'RTX 4070', label: 'GeForce RTX 4070' },
    { value: 'RTX 4080', label: 'GeForce RTX 4080' },
    { value: 'RTX 4090', label: 'GeForce RTX 4090' },
  ],
  ram: [
    { value: '16GB', label: '16 ГБ' },
    { value: '32GB', label: '32 ГБ' },
    { value: '64GB', label: '64 ГБ' },
    { value: '128GB', label: '128 ГБ' },
  ],
  priceRange: {
    min: 50000,
    max: 500000,
  },
};

export const sortOptions = [
  { value: 'popularity', label: 'По популярности' },
  { value: 'price-asc', label: 'Сначала дешевле' },
  { value: 'price-desc', label: 'Сначала дороже' },
  { value: 'newest', label: 'Новинки' },
];
