// VA-PC Products Data - 37 PC configurations
// Imported from original site

export interface Product {
  id: number;
  title: string;
  slug: string;
  image: string;
  cpu: string;
  gpu: string;
  ram: string;
  storage: string;
  cooling: string;
  psu: string;
  price: number;
  priceFormatted: string;
  category: 'budget' | 'gaming' | 'performance' | 'premium' | 'ultra';
}

const imageMap: Record<string, string> = {
  'phoenix': '/images/products/phoenix.png',
  'electra': '/images/products/electra.png',
  'zen': '/images/products/zen.png',
  'aurora': '/images/products/aurora.png',
  'pulse': '/images/products/pulse.png',
  'vortex': '/images/products/vortex.png',
  'fusion': '/images/products/fusion.png',
  'nexus': '/images/products/nexus.png',
  'blaze': '/images/products/blaze.png',
  'vanguard': '/images/products/vandguard.png',
  'nova': '/images/products/nova.png',
  'nebula': '/images/products/nebula.png',
  'punk': '/images/products/punk.png',
  'neo': '/images/products/neo.png',
  'titan': '/images/products/titan.png',
  'apex': '/images/products/apex.png',
  'enigma': '/images/products/enigma.png',
  'dynamic': '/images/products/dynamic.png',
  'silver': '/images/products/silver.png',
  'orion': '/images/products/orion.png',
  'eclipse': '/images/products/eclipse.png',
  'eagle': '/images/products/eagle.png',
  'master': '/images/products/master.png',
  'ultra': '/images/products/ultra.png',
  'rose': '/images/products/rose.png',
  'fury': '/images/products/electraR.png',
  'pulse-r-plus': '/images/products/pulseR.png',
  'cyber': '/images/products/cyber.png',
  'raptor': '/images/products/vanguardR.png',
  'astral': '/images/products/astral.png',
  'prism': '/images/products/prism.png',
  'alpha': '/images/products/alpha.png',
  'impact': '/images/products/synergyX.png',
  'frost': '/images/products/vanguardMini.png',
  'aero': '/images/products/aero.png',
  'synergy': '/images/products/synergy.png',
  'prime': '/images/products/vanguard2.png',
};

function getCategory(price: number): Product['category'] {
  if (price < 60000) return 'budget';
  if (price < 100000) return 'gaming';
  if (price < 180000) return 'performance';
  if (price < 300000) return 'premium';
  return 'ultra';
}

function formatPrice(price: number): string {
  return new Intl.NumberFormat('ru-RU').format(price) + ' ₽';
}

function createSlug(title: string): string {
  return title.toLowerCase().replace(/\s+/g, '-').replace('va-', '');
}

export const products: Product[] = [
  {
    id: 1,
    title: 'VA PHOENIX',
    slug: 'phoenix',
    image: imageMap['phoenix'],
    cpu: 'Ryzen 3 1200',
    gpu: 'GTX 1650',
    ram: '16GB DDR4',
    storage: '480GB',
    cooling: 'AG200',
    psu: '400W',
    price: 42000,
    priceFormatted: formatPrice(42000),
    category: getCategory(42000),
  },
  {
    id: 2,
    title: 'VA ELECTRA',
    slug: 'electra',
    image: imageMap['electra'],
    cpu: 'i3-10105F',
    gpu: 'GTX 1650',
    ram: '16GB DDR4',
    storage: '480GB',
    cooling: 'AG200',
    psu: '400W',
    price: 44000,
    priceFormatted: formatPrice(44000),
    category: getCategory(44000),
  },
  {
    id: 25,
    title: 'VA ROSE',
    slug: 'rose',
    image: imageMap['rose'],
    cpu: 'i3-12100F',
    gpu: 'GTX 1650',
    ram: '16GB DDR4',
    storage: '240GB',
    cooling: 'AG200',
    psu: '500W',
    price: 49000,
    priceFormatted: formatPrice(49000),
    category: getCategory(49000),
  },
  {
    id: 3,
    title: 'VA ZEN',
    slug: 'zen',
    image: imageMap['zen'],
    cpu: 'i3-12100f',
    gpu: 'GTX 1660',
    ram: '16GB DDR4',
    storage: '1TB',
    cooling: 'AG300',
    psu: '500W',
    price: 59000,
    priceFormatted: formatPrice(59000),
    category: getCategory(59000),
  },
  {
    id: 4,
    title: 'VA AURORA',
    slug: 'aurora',
    image: imageMap['aurora'],
    cpu: 'i3-12100f',
    gpu: 'GTX 1660',
    ram: '16GB DDR4',
    storage: '1TB',
    cooling: 'AG300',
    psu: '500W',
    price: 61000,
    priceFormatted: formatPrice(61000),
    category: getCategory(61000),
  },
  {
    id: 5,
    title: 'VA PULSE',
    slug: 'pulse',
    image: imageMap['pulse'],
    cpu: 'i3-12100f',
    gpu: 'RTX 3050',
    ram: '16GB DDR4',
    storage: '1TB',
    cooling: 'AG200',
    psu: '500W',
    price: 63000,
    priceFormatted: formatPrice(63000),
    category: getCategory(63000),
  },
  {
    id: 6,
    title: 'VA VORTEX',
    slug: 'vortex',
    image: imageMap['vortex'],
    cpu: 'i3-12100f',
    gpu: 'RTX 3050',
    ram: '16GB DDR4',
    storage: '1TB',
    cooling: 'AG200',
    psu: '500W',
    price: 65000,
    priceFormatted: formatPrice(65000),
    category: getCategory(65000),
  },
  {
    id: 7,
    title: 'VA FUSION',
    slug: 'fusion',
    image: imageMap['fusion'],
    cpu: 'i3-12100f',
    gpu: 'RTX 2060',
    ram: '16GB DDR4',
    storage: '1TB',
    cooling: 'AG300',
    psu: '600W',
    price: 69000,
    priceFormatted: formatPrice(69000),
    category: getCategory(69000),
  },
  {
    id: 26,
    title: 'VA FURY',
    slug: 'fury',
    image: imageMap['fury'],
    cpu: 'Ryzen 5 5500',
    gpu: 'RTX 2060',
    ram: '16GB DDR4',
    storage: '512GB M2',
    cooling: 'SE-224-XTS',
    psu: '600W',
    price: 75000,
    priceFormatted: formatPrice(75000),
    category: getCategory(75000),
  },
  {
    id: 27,
    title: 'VA PULSE R+',
    slug: 'pulse-r-plus',
    image: imageMap['pulse-r-plus'],
    cpu: 'Ryzen 5 5500',
    gpu: 'RTX 3060',
    ram: '16GB DDR4',
    storage: '512GB M2',
    cooling: 'SE-224-XTS',
    psu: '750W',
    price: 82200,
    priceFormatted: formatPrice(82200),
    category: getCategory(82200),
  },
  {
    id: 8,
    title: 'VA NEXUS',
    slug: 'nexus',
    image: imageMap['nexus'],
    cpu: 'i5-12400f',
    gpu: 'RTX 3060',
    ram: '16GB DDR4',
    storage: '1TB M2',
    cooling: 'SE-224-XTS',
    psu: '600W',
    price: 89400,
    priceFormatted: formatPrice(89400),
    category: getCategory(89400),
  },
  {
    id: 28,
    title: 'VA CYBER',
    slug: 'cyber',
    image: imageMap['cyber'],
    cpu: 'Ryzen 5 5600',
    gpu: 'RTX 3060',
    ram: '32GB DDR4',
    storage: '512GB M2',
    cooling: 'SE-224-XTS',
    psu: '750W',
    price: 89400,
    priceFormatted: formatPrice(89400),
    category: getCategory(89400),
  },
  {
    id: 29,
    title: 'VA RAPTOR',
    slug: 'raptor',
    image: imageMap['raptor'],
    cpu: 'Ryzen 5 5500',
    gpu: 'RTX 3060 TI',
    ram: '32GB DDR4',
    storage: '512GB M2',
    cooling: 'SE-224-XTS',
    psu: '750W',
    price: 90500,
    priceFormatted: formatPrice(90500),
    category: getCategory(90500),
  },
  {
    id: 30,
    title: 'VA ASTRAL',
    slug: 'astral',
    image: imageMap['astral'],
    cpu: 'Ryzen 5 5600',
    gpu: 'RTX 3060 TI',
    ram: '32GB DDR4',
    storage: '512GB M2',
    cooling: 'SE-224-XTS',
    psu: '750W',
    price: 97700,
    priceFormatted: formatPrice(97700),
    category: getCategory(97700),
  },
  {
    id: 9,
    title: 'VA BLAZE',
    slug: 'blaze',
    image: imageMap['blaze'],
    cpu: 'i5-12400f',
    gpu: 'RTX 3060 TI',
    ram: '16GB DDR4',
    storage: '1TB',
    cooling: 'SE-224-XTS',
    psu: '700W',
    price: 99900,
    priceFormatted: formatPrice(99900),
    category: getCategory(99900),
  },
  {
    id: 31,
    title: 'VA PRISM',
    slug: 'prism',
    image: imageMap['prism'],
    cpu: 'Ryzen 5 5600',
    gpu: 'RTX 3070 OC',
    ram: '32GB DDR4',
    storage: '512GB M2',
    cooling: 'SE-224-XTS',
    psu: '750W',
    price: 102900,
    priceFormatted: formatPrice(102900),
    category: getCategory(102900),
  },
  {
    id: 34,
    title: 'VA FROST',
    slug: 'frost',
    image: imageMap['frost'],
    cpu: 'i5-12400f',
    gpu: 'RTX 3060 TI',
    ram: '32GB DDR4',
    storage: '512GB',
    cooling: 'L240',
    psu: '750W',
    price: 108200,
    priceFormatted: formatPrice(108200),
    category: getCategory(108200),
  },
  {
    id: 10,
    title: 'VA VANGUARD',
    slug: 'vanguard',
    image: imageMap['vanguard'],
    cpu: 'i5-12400f',
    gpu: 'RTX 3070',
    ram: '32GB DDR4',
    storage: '2TB',
    cooling: 'SE-224-XTS',
    psu: '700W',
    price: 115400,
    priceFormatted: formatPrice(115400),
    category: getCategory(115400),
  },
  {
    id: 11,
    title: 'VA NOVA',
    slug: 'nova',
    image: imageMap['nova'],
    cpu: 'i5-12600KF',
    gpu: 'RTX 3060 TI',
    ram: '32GB DDR4',
    storage: '1TB',
    cooling: 'L240',
    psu: '700W',
    price: 143500,
    priceFormatted: formatPrice(143500),
    category: getCategory(143500),
  },
  {
    id: 37,
    title: 'VA PRIME',
    slug: 'prime',
    image: imageMap['prime'],
    cpu: 'i5-13400f',
    gpu: 'RTX 4070 TI',
    ram: '32GB DDR4',
    storage: '512GB M2',
    cooling: 'SE-224-XTS',
    psu: '750W',
    price: 149700,
    priceFormatted: formatPrice(149700),
    category: getCategory(149700),
  },
  {
    id: 12,
    title: 'VA NEBULA',
    slug: 'nebula',
    image: imageMap['nebula'],
    cpu: 'i5-12600KF',
    gpu: 'RTX 3070 TI',
    ram: '32GB DDR4',
    storage: '1TB',
    cooling: 'L240',
    psu: '700W',
    price: 155000,
    priceFormatted: formatPrice(155000),
    category: getCategory(155000),
  },
  {
    id: 32,
    title: 'VA ALPHA',
    slug: 'alpha',
    image: imageMap['alpha'],
    cpu: 'i5-13400f',
    gpu: 'RTX 4070 TI',
    ram: '32GB DDR4',
    storage: '1TB M2',
    cooling: 'SE-224-XTS',
    psu: '750W',
    price: 156000,
    priceFormatted: formatPrice(156000),
    category: getCategory(156000),
  },
  {
    id: 13,
    title: 'VA PUNK',
    slug: 'punk',
    image: imageMap['punk'],
    cpu: 'i5-13400F',
    gpu: 'RTX 4070',
    ram: '32GB DDR4',
    storage: '1TB',
    cooling: 'SE-224-XTS',
    psu: '750W',
    price: 162200,
    priceFormatted: formatPrice(162200),
    category: getCategory(162200),
  },
  {
    id: 33,
    title: 'VA IMPACT',
    slug: 'impact',
    image: imageMap['impact'],
    cpu: 'i5-13600KF',
    gpu: 'RTX 4070 TI',
    ram: '32GB DDR5',
    storage: '2TB',
    cooling: 'L360',
    psu: '750W',
    price: 186200,
    priceFormatted: formatPrice(186200),
    category: getCategory(186200),
  },
  {
    id: 14,
    title: 'VA NEO',
    slug: 'neo',
    image: imageMap['neo'],
    cpu: 'i5-12600KF',
    gpu: 'RTX 4070 TI',
    ram: '32GB DDR4',
    storage: '1TB',
    cooling: 'ZFLOW 360XT',
    psu: '750W',
    price: 192400,
    priceFormatted: formatPrice(192400),
    category: getCategory(192400),
  },
  {
    id: 35,
    title: 'VA AERO',
    slug: 'aero',
    image: imageMap['aero'],
    cpu: 'i7-13700KF',
    gpu: 'RTX 4070 TI',
    ram: '32GB DDR4',
    storage: '1TB M2',
    cooling: 'LT720',
    psu: '850W',
    price: 202800,
    priceFormatted: formatPrice(202800),
    category: getCategory(202800),
  },
  {
    id: 15,
    title: 'VA TITAN',
    slug: 'titan',
    image: imageMap['titan'],
    cpu: 'i5-13500',
    gpu: 'RTX 4070 TI',
    ram: '32GB DDR4',
    storage: '1TB',
    cooling: 'LT720',
    psu: '750W',
    price: 205900,
    priceFormatted: formatPrice(205900),
    category: getCategory(205900),
  },
  {
    id: 36,
    title: 'VA SYNERGY',
    slug: 'synergy',
    image: imageMap['synergy'],
    cpu: 'i5-13500',
    gpu: 'RTX 4080',
    ram: '32GB DDR5',
    storage: '1TB M2',
    cooling: 'L360',
    psu: '850W',
    price: 206900,
    priceFormatted: formatPrice(206900),
    category: getCategory(206900),
  },
  {
    id: 16,
    title: 'VA APEX',
    slug: 'apex',
    image: imageMap['apex'],
    cpu: 'i5-13600KF',
    gpu: 'RTX 4070 TI',
    ram: '32GB DDR4',
    storage: '1TB',
    cooling: 'II-360',
    psu: '750W',
    price: 214200,
    priceFormatted: formatPrice(214200),
    category: getCategory(214200),
  },
  {
    id: 17,
    title: 'VA ENIGMA',
    slug: 'enigma',
    image: imageMap['enigma'],
    cpu: 'i5-13600KF',
    gpu: 'RTX 4080',
    ram: '32GB DDR4',
    storage: '1TB',
    cooling: 'II-360',
    psu: '850W',
    price: 236100,
    priceFormatted: formatPrice(236100),
    category: getCategory(236100),
  },
  {
    id: 18,
    title: 'VA DYNAMIC',
    slug: 'dynamic',
    image: imageMap['dynamic'],
    cpu: 'i5-13600KF',
    gpu: 'RTX 4080 OC',
    ram: '32GB DDR4',
    storage: '2TB',
    cooling: 'II-360',
    psu: '850W',
    price: 265200,
    priceFormatted: formatPrice(265200),
    category: getCategory(265200),
  },
  {
    id: 19,
    title: 'VA SILVER',
    slug: 'silver',
    image: imageMap['silver'],
    cpu: 'i7-13700KF',
    gpu: 'RTX 4080 OC',
    ram: '32GB DDR4',
    storage: '2TB',
    cooling: 'S360',
    psu: '850W',
    price: 282900,
    priceFormatted: formatPrice(282900),
    category: getCategory(282900),
  },
  {
    id: 20,
    title: 'VA ORION',
    slug: 'orion',
    image: imageMap['orion'],
    cpu: 'i7-13700KF',
    gpu: 'RTX 4090',
    ram: '32GB DDR4',
    storage: '2TB',
    cooling: 'S360',
    psu: '1200W',
    price: 297500,
    priceFormatted: formatPrice(297500),
    category: getCategory(297500),
  },
  {
    id: 21,
    title: 'VA ECLIPSE',
    slug: 'eclipse',
    image: imageMap['eclipse'],
    cpu: 'i9-13900KF',
    gpu: 'RTX 4090',
    ram: '32GB DDR4',
    storage: '2TB',
    cooling: 'S360',
    psu: '1200W',
    price: 346300,
    priceFormatted: formatPrice(346300),
    category: getCategory(346300),
  },
  {
    id: 22,
    title: 'VA EAGLE',
    slug: 'eagle',
    image: imageMap['eagle'],
    cpu: 'i9-13900KF',
    gpu: 'RTX 4090 OC',
    ram: '32GB DDR5',
    storage: '2TB',
    cooling: 'S360',
    psu: '1200W',
    price: 393100,
    priceFormatted: formatPrice(393100),
    category: getCategory(393100),
  },
  {
    id: 23,
    title: 'VA MASTER',
    slug: 'master',
    image: imageMap['master'],
    cpu: 'i9-13900KF',
    gpu: 'RTX 4090',
    ram: '32GB DDR5',
    storage: '2TB',
    cooling: 'II 360',
    psu: '1200W',
    price: 403500,
    priceFormatted: formatPrice(403500),
    category: getCategory(403500),
  },
  {
    id: 24,
    title: 'VA ULTRA',
    slug: 'ultra',
    image: imageMap['ultra'],
    cpu: 'i9-13900KF',
    gpu: 'RTX 4090',
    ram: '64GB DDR5',
    storage: '2TB',
    cooling: 'II 360',
    psu: '1200W',
    price: 464900,
    priceFormatted: formatPrice(464900),
    category: getCategory(464900),
  },
].sort((a, b) => a.price - b.price);

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: Product['category']): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(count: number = 6): Product[] {
  // Return a mix of products from different categories
  const budget = products.filter(p => p.category === 'budget').slice(0, 1);
  const gaming = products.filter(p => p.category === 'gaming').slice(0, 2);
  const performance = products.filter(p => p.category === 'performance').slice(0, 2);
  const premium = products.filter(p => p.category === 'premium').slice(0, 1);

  return [...budget, ...gaming, ...performance, ...premium].slice(0, count);
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase();
  return products.filter((p) =>
    p.title.toLowerCase().includes(lowercaseQuery) ||
    p.cpu.toLowerCase().includes(lowercaseQuery) ||
    p.gpu.toLowerCase().includes(lowercaseQuery)
  );
}

export const categoryLabels: Record<Product['category'], string> = {
  budget: 'Бюджетные',
  gaming: 'Игровые',
  performance: 'Производительные',
  premium: 'Премиум',
  ultra: 'Ультра',
};
